language: node_js
node_js:
  - 6
  - lts/*
  - node
install:
  - '[ -z "$REACT_VERSION" ] || npm run peer:react -- $REACT_VERSION'
  - npm ci
jobs:
  include:
    - name: lint
      node_js: lts/*
      script: npm run lint
    - node_js: node
      env: REACT_VERSION=0.14.3
    - node_js: node
      env: REACT_VERSION=15.6.1
    - node_js: node
      env: REACT_VERSION=16.0.0
