name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: npm install and lint
        run: |
          npm ci
          npm run lint
        env:
          CI: true
